@startuml Login
participant WebClient #lightgreen
participant Auth0 #orange
participant IDP #cyan
participant Acquaa #lightblue

WebClient -> Auth0 : user logs in
Auth0 -> IDP : redirect to IDP for authentication
IDP --> Auth0 : authenticate user
Auth0 --> Acquaa : callback with authorization code
Acquaa -> Auth0 : validate code
Auth0 --> Acquaa : code validated

Acquaa --> WebClient : refresh token (stored in secure cookie)

WebClient -> Acquaa : request access token (with refresh token)
Acquaa --> WebClient : access token (with permissions explicitly specified)

WebClient -> Acquaa : request resource (with access token)
Acquaa --> WebClient : response

@enduml